services:
  client:
    stdin_open: true
    image: protokollitaja-web-client
    container_name: protokollitaja-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data:/data
    networks:
      - backend

  db:
    image: mongo:8.2.3
    restart: always
    container_name: protokollitaja-mongo
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb
      - /data/protokollitaja-backup:/backup
    environment:
      TZ: "Europe/Tallinn"
    networks:
      - backend

  protokollitaja-backend:
    image: protokollitaja-backend
    volumes:
      - /data:/data
    ports:
      - 3004:3004
      - 3005:3005
    environment:
      TZ: "Europe/Tallinn"
    env_file:
      - ./../protokollitaja-backend.env
    container_name: protokollitaja-backend
    restart: always
    networks:
      - backend
    depends_on:
      - db

networks:
  backend:

volumes:
  mongo-data:
    name: mongo-data
  mongo-configdb:
    name: mongo-configdb
